# Generated by Django 4.2.1 on 2023-05-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('people', models.CharField(max_length=10)),
                ('confirm', models.CharField(choices=[('A', 'Abia astept'), ('N', 'Nu pot veni')], max_length=128)),
            ],
        ),
    ]
